- name: Install NFS client packages
  apt:
    name: nfs-common
    state: present
    update_cache: yes

- name: Create mount point
  file:
    path: /mnt/nfs_share
    state: directory

- name: Mount NFS share
  mount:
    path: /mnt/nfs_share
    src: "10.215.19.10:/data/nfs_share"
    fstype: nfs
    opts: rw
    state: mounted